name: release

on:
  release:
    types: [ prereleased, released ]

jobs:
  release:
    name: Release Build
    runs-on: ubuntu-latest
    steps:
      # Check out repository
      - name: Fetch Sources
        uses: actions/checkout@v4
      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.1.0
      # Set up Java environment
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      # Build plugin
      - name: Build plugin
        run: ./gradlew buildPlugin -PisRelease=true
      # Attach Artifact
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/distributions/*.zip
      ## upload plugin as a release asset
      - name: Upload Release Asset
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./build/distributions/*